#########################################################################
# Title:         Saltbox: Plex Extra Tasks | Default Variables          #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
plex_extra_tasks_hostname: "{{ plex_name
                            if not ('container:' in lookup('vars', plex_name + '_docker_network_mode_default', default=docker_networks_name_common))
                            else (lookup('vars', plex_name + '_docker_network_mode_default', default=docker_networks_name_common).split(':')[1]) }}"
