############################################################################
# Title:         Saltbox: Resources | Tasks | Instances | Get Readarr Info #
# Author(s):     salty                                                     #
# URL:           https://github.com/saltyorg/Saltbox                       #
# --                                                                       #
############################################################################
#                   GNU General Public License v3.0                        #
############################################################################
---
- name: Resources | Tasks | Instances | Get Info | Check if Readarr exists
  ansible.builtin.stat:
    path: "{{ readarr_paths_config_location }}"
  register: readarr_paths_config_location_stat

- name: Resources | Tasks | Instances | Get Info | Readarr API Key tasks
  when: readarr_paths_config_location_stat.stat.exists
  block:
    - name: Resources | Tasks | Instances | Get Info | Fetch Readarr API Key
      community.general.xml:
        path: "{{ readarr_paths_config_location }}"
        xpath: /Config/ApiKey
        content: text
      register: xmlresp

    - name: Resources | Tasks | Instances | Get Info | Set 'readarr_info' variable
      ansible.builtin.set_fact:
        readarr_info: "{{ readarr_info | default({}) | combine({readarr_name: {'name': readarr_name, 'url': readarr_web_url, 'api_key': xmlresp.matches[0].ApiKey}}) }}"

- name: Resources | Tasks | Instances | Get Info | Set 'readarr_info' variable
  ansible.builtin.set_fact:
    readarr_info: "{{ readarr_info | default({}) | combine({readarr_name: {'name': readarr_name, 'url': readarr_web_url, 'api_key': 'not installed'}}) }}"
  when: (not readarr_paths_config_location_stat.stat.exists)
