#########################################################################
# Title:         Saltbox: UnionFS | Legacy Tasks                        #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check if 'mergerfs.service' exists"
  ansible.builtin.stat:
    path: "/etc/systemd/system/mergerfs.service"
  register: mergerfs_status

- name: "Tasks for 'mergerfs.service'"
  when: mergerfs_status.stat.exists
  block:
    - name: "Stop and disable existing 'mergerfs.service'"
      ansible.builtin.systemd_service:
        name: "mergerfs.service"
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Delete 'mergerfs.service'
      ansible.builtin.file:
        path: "/etc/systemd/system/mergerfs.service"
        state: absent
