##########################################################################
# Title:         Saltbox: UnionFS | Variable Tasks                       #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Remotes List
################################
- name: Variables | Set '_remotes_list' variable
  ansible.builtin.set_fact:
    _remotes_list: "{{ _remotes_list | default('') + '/mnt/remote/' + (item.remote.split(':')[0] if ':' in item.remote else item.remote) + '=' + mergerfs_remote_branch_mode_lookup + ':' }}"
  with_items: "{{ rclone.remotes }}"
  when: rclone_remote_is_defined and use_remote and item.settings.mount and item.settings.union

- name: Variables | Append 'custom_mount_branch' to '_remotes_list' variable
  ansible.builtin.set_fact:
    _remotes_list: "{{ _remotes_list | default('') + custom_mount_branch }}"

- name: Variables | Remove trailing colon in '_remotes_list'
  ansible.builtin.set_fact:
    _remotes_list: "{{ _remotes_list[:-1] }}"
  when: (_remotes_list is defined) and (_remotes_list | length > 0) and (_remotes_list[-1] == ':')
