#########################################################################
# Title:         Saltbox: Sanity Check | Temp Folder                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Tmp | Create Ansible Temp directory
  ansible.builtin.file:
    path: "/tmp/ansible"
    state: directory
    mode: "0777"
    owner: "root"
    group: "root"
