#########################################################################
# Title:         Saltbox: Sanity Check | Repository Check               #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Repository | Get Git Branch
  ansible.builtin.shell: git rev-parse --abbrev-ref HEAD
  register: git_branch

- name: Repository | Check Git Hash
  ansible.builtin.shell: git rev-parse HEAD
  register: git_version

- name: Repository | Check Git Origin Hash
  ansible.builtin.shell: "curl -L --connect-timeout 2.37 -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' {{ svm }}https://api.github.com/repos/saltyorg/Saltbox/commits?sha={{ git_branch.stdout }} | jq -r '.[0][\"sha\"]'"
  register: git_origin_version
  ignore_errors: true

- name: Repository | Print Git Hash
  ansible.builtin.debug:
    msg: "Commit: {{ git_version.stdout }}"

- name: Repository | Saltbox Up to Date
  ansible.builtin.debug:
    msg: "Saltbox is running the latest commit for branch: {{ git_branch.stdout }}"
  when: (git_origin_version.stdout | length > 0) and (git_version.stdout == git_origin_version.stdout)

- name: Repository | Saltbox Outdated
  ansible.builtin.debug:
    msg: "Saltbox is not using the newest commit for branch: {{ git_branch.stdout }} - {{ git_origin_version.stdout }}"
  when: (git_origin_version.stdout | length > 0) and (git_version.stdout != git_origin_version.stdout)
