#########################################################################
# Title:            Saltbox: Common                                     #
# Author(s):        salty                                               #
# URL:              https://github.com/saltyorg/Saltbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
nano_syntax_highlighting_enabled: true
common_create_media_subfolders: true
