##########################################################################
# Title:         Saltbox: Saltbox/Mediabox/Feederbox | Default Variables #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
saltbox_roles: ["media_server", "download_clients", "download_indexers", "tautulli", "overseerr", "portainer", "organizr", "sonarr", "radarr", "lidarr", "iperf3", "nethogs", "glances", "btop"]
mediabox_roles: ["media_server", "tautulli", "overseerr", "iperf3", "nethogs", "glances", "btop"]
feederbox_roles: ["download_clients", "download_indexers", "portainer", "organizr", "sonarr", "radarr", "lidarr", "iperf3", "nethogs", "glances", "btop"]
