##########################################################################
# Title:         Saltbox: Arr DB | Default Variables                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Settings
################################
arr_db_sonarr_enabled: false
arr_db_radarr_enabled: false
arr_db_lidarr_enabled: false
arr_db_readarr_enabled: false
arr_db_whisparr_enabled: false
arr_db_prowlarr_enabled: false
arr_db_tautulli_enabled: false

################################
# Variables
################################

arr_path_logs_db: "{{ lookup('vars', arr_type + '_paths_location') }}/logs.db"
arr_path_main_db: "{{ lookup('vars', arr_type + '_paths_location') }}/{{ arr_type }}.db"
arr_db_files:
  - "logs.db"
  - "{{ arr_type }}.db"
arr_db_temp_files:
  - "logs.db-wal"
  - "logs.db-shm"
  - "{{ arr_type }}.db-wal"
  - "{{ arr_type }}.db-shm"

arr_db_tautulli_database: "tautulli.db"
arr_db_tautulli_temp_files:
  - "tautulli.db-wal"
  - "tautulli.db-shm"
