##########################################################################
# Title:         Saltbox: Custom                                         #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Install custom apt packages
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  ignore_errors: true
  loop: "{{ custom_apt }}"

- name: Install custom deb packages
  ansible.builtin.apt:
    state: present
    deb: "{{ item }}"
  ignore_errors: true
  loop: "{{ custom_deb }}"

- name: Install custom pip modules
  ansible.builtin.shell: "pip install {{ item }}"
  ignore_errors: true
  loop: "{{ custom_pip }}"
