#########################################################################
# Title:         Saltbox: Download Clients Role                         #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Download Client roles"
  ansible.builtin.include_role:
    name: "{{ download_client_role }}"
  with_items: "{{ download_clients_enabled }}"
  loop_control:
    loop_var: download_client_role
