#########################################################################
# Title:         Saltbox: Saltbox/Mediabox/Feederbox Role               #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Saltbox roles"
  ansible.builtin.include_role:
    name: "{{ saltbox_role }}"
  with_items: "{{ saltbox_roles }}"
  loop_control:
    loop_var: saltbox_role
  when: ('saltbox' in ansible_run_tags)

- name: "Execute Mediabox roles"
  ansible.builtin.include_role:
    name: "{{ mediabox_role }}"
  with_items: "{{ mediabox_roles }}"
  loop_control:
    loop_var: mediabox_role
  when: ('mediabox' in ansible_run_tags)

- name: "Execute Feederbox roles"
  ansible.builtin.include_role:
    name: "{{ feederbox_role }}"
  with_items: "{{ feederbox_roles }}"
  loop_control:
    loop_var: feederbox_role
  when: ('feederbox' in ansible_run_tags)
