#########################################################################
# Title:         Saltbox: System | sysctl Tasks                         #
# Author(s):     l3uddz, desimaniac, salty                              #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: sysctl | Tuning
  ignore_errors: true
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ sysctl_settings | dict2items }}"

- name: sysctl | Check to see if '/proc/sys/net/core/netdev_budget_usecs' exists
  ansible.builtin.stat:
    path: "/proc/sys/net/core/netdev_budget_usecs"
  register: netdev_budget_usecs

- name: "sysctl | Tuning - 'netdev_budget_usecs'"
  ignore_errors: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    # Set netdev_budget_usecs
    - { name: net.core.netdev_budget_usecs, value: 5000 }
  when: netdev_budget_usecs.stat.exists
