#########################################################################
# Title:         Saltbox: Docker | DNS Tasks                            #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: DNS | Cleanup 'docker-update-hosts.service'
  ansible.builtin.systemd_service:
    name: docker-update-hosts
    state: stopped
    enabled: false
  when: (services['docker-update-hosts.service'] is defined)

- name: DNS | Remove docker-update-hosts.service
  ansible.builtin.file:
    path: /etc/systemd/system/docker-update-hosts.service
    state: absent

- name: DNS | Import 'docker-update-hosts'
  ansible.builtin.copy:
    src: docker-update-hosts
    force: true
    dest: "/usr/local/bin/docker-update-hosts"
    owner: "root"
    group: "root"
    mode: "0755"

- name: DNS | Set 'docker-update-hosts' as executable
  ansible.builtin.file:
    path: /usr/local/bin/docker-update-hosts
    owner: "root"
    group: "root"
    mode: a+x

- name: DNS | Import 'saltbox_managed_docker_update_hosts.service'
  ansible.builtin.template:
    src: docker-update-hosts.service.j2
    dest: /etc/systemd/system/saltbox_managed_docker_update_hosts.service
    mode: "0644"
    force: true

- name: DNS | Start 'saltbox_managed_docker_update_hosts.service'
  ansible.builtin.systemd_service:
    name: saltbox_managed_docker_update_hosts
    state: restarted
    enabled: true
    daemon_reload: true
