#########################################################################
# Title:         Saltbox: MariaDB Role                                  #
# Author(s):     desimaniac, l3uddz, salty, owine                       #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute MariaDB roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    mariadb_name: "{{ role }}"
  with_items: "{{ mariadb_instances }}"
  loop_control:
    loop_var: role
