#########################################################################
# Title:         Saltbox: MariaDB Role                                  #
# Author(s):     desimaniac, l3uddz, salty, owine                       #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Pre-Migration tasks
  ansible.builtin.include_tasks: pre-migration.yml
  when: mariadb_name == "mariadb"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Post-Migration tasks
  ansible.builtin.include_tasks: post-migration.yml
  when: mariadb_name == "mariadb"

- name: Sleep for 30 seconds
  ansible.builtin.wait_for:
    timeout: 30
