#########################################################################
# Title:         Saltbox: Plex Auth Token Role                          #
# Author(s):     EnorMOZ, Desimaniac, salty                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check if Plex instance is defined
  ansible.builtin.set_fact:
    plex_name: "{{ plex_name | default(plex_instances[0]) }}"

- name: "Auth Token | Create directories"
  ansible.builtin.file:
    path: "/opt/saltbox"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"

- name: "Auth Token | Check if PIN exists"
  ansible.builtin.stat:
    path: "/opt/saltbox/plex.ini"
  register: plex_ini

- name: "Auth Token | plex_auth_client_identifier"
  when: plex_ini.stat.exists
  block:
    - name: "Auth Token | Lookup plex_auth_client_identifier"
      ansible.builtin.set_fact:
        plex_auth_client_identifier: "{{ lookup('ini', 'client_identifier section=' + plex_name + ' file=/opt/saltbox/plex.ini') }}"
        plex_auth_client_identifier_missing: false

  rescue:
    - name: "Auth Token | Set plex_auth_client_identifier to empty string"
      ansible.builtin.set_fact:
        plex_auth_client_identifier: ""
        plex_auth_client_identifier_missing: true

- name: "Auth Token | Generate new plex_auth_client_identifier"
  ansible.builtin.set_fact:
    plex_auth_client_identifier: "Saltbox{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
  when: (not plex_ini.stat.exists) or plex_auth_client_identifier_missing

- name: "Auth Token | Set plex_auth_token variable if previously saved"
  ansible.builtin.set_fact:
    plex_auth_token: "{{ lookup('ini', 'token section=' + plex_name + ' file=/opt/saltbox/plex.ini') | regex_replace('\n', '') }}"
  when: plex_ini.stat.exists and (not plex_auth_client_identifier_missing)

- name: "Auth Token | Set plex_no_token status"
  ansible.builtin.set_fact:
    plex_no_token: "{{ (not plex_ini.stat.exists) or plex_auth_client_identifier_missing | ternary(true, false) }}"

- name: "Auth Token | Check if Token is valid"
  ansible.builtin.uri:
    url: "https://plex.tv/api/v2/user"
    method: GET
    return_content: yes
    body:
      X-Plex-Token: "{{ lookup('ini', 'token section=' + plex_name + ' file=/opt/saltbox/plex.ini') }}"
      X-Plex-Version: "{{ plex_auth_token_version }}"
      X-Plex-Product: "{{ plex_auth_token_product }}"
      X-Plex-Client-Identifier: "{{ plex_auth_client_identifier }}"
    body_format: form-urlencoded
    headers:
      Accept: "application/json"
    status_code: [200, 401]
  environment: "{{ plex_proxy_dict }}"
  register: plex_token
  when: plex_ini.stat.exists and (not plex_auth_client_identifier_missing)

- name: "Auth Token | Generate New Token"
  when: plex_no_token or (plex_token.status == 401)
  block:
    - name: "Auth Token | Generate PIN"
      ansible.builtin.uri:
        url: "https://plex.tv/api/v2/pins"
        method: POST
        return_content: yes
        body:
          strong: "true"
          X-Plex-Version: "{{ plex_auth_token_version }}"
          X-Plex-Product: "{{ plex_auth_token_product }}"
          X-Plex-Client-Identifier: "{{ plex_auth_client_identifier }}"
        body_format: form-urlencoded
        headers:
          Accept: "application/json"
        status_code: 201
      environment: "{{ plex_proxy_dict }}"
      register: plex_pin

    - name: "Auth Token | Prompt user to login"
      ansible.builtin.pause:
        prompt: "Please open https://app.plex.tv/auth#?clientID={{ plex_pin.json.clientIdentifier }}&code={{ plex_pin.json.code }}&context%5Bdevice%5D%5Bproduct%5D={{ plex_pin.json.product }} and login. Hit enter after having logged in"  # noqa 204 line-length

    - name: "Auth Token | Check PIN"
      ansible.builtin.uri:
        url: "https://plex.tv/api/v2/pins/{{ plex_pin.json.id }}"
        method: GET
        return_content: yes
        body:
          X-Plex-Client-Identifier: "{{ plex_auth_client_identifier }}"
        body_format: form-urlencoded
        headers:
          Accept: "application/json"
        status_code: 200
      environment: "{{ plex_proxy_dict }}"
      register: plex_token_new

    - name: "Auth Token | Add Client Identifier to '/opt/saltbox/plex.ini'"
      community.general.ini_file:
        path: /opt/saltbox/plex.ini
        section: "{{ plex_name }}"
        option: client_identifier
        value: "{{ plex_auth_client_identifier }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0664"

    - name: "Auth Token | Add Plex Token to '/opt/saltbox/plex.ini'"
      community.general.ini_file:
        path: /opt/saltbox/plex.ini
        section: "{{ plex_name }}"
        option: token
        value: "{{ plex_token_new.json.authToken }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0664"

    - name: "Auth Token | Set plex_auth_token variable"
      ansible.builtin.set_fact:
        plex_auth_token: "{{ plex_token_new.json.authToken | regex_replace('\n', '') }}"

- name: "Auth Token | Display Plex Auth Token"
  ansible.builtin.debug:
    msg: "Plex Auth Token: {{ plex_auth_token }}"

- name: Change permissions
  ansible.builtin.file:
    path: /opt/saltbox
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
    recurse: true
