#########################################################################
# Title:         Saltbox: yyq Role | Defaults Variables                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
yyq_install_version: "4.35.2"
