#############################################################################
# Title:         Saltbox: DNS | Cloudflare | Add DNS Record | IPv6 Disabled #
# Author(s):     salty                                                      #
# URL:           https://github.com/saltyorg/Saltbox                        #
# --                                                                        #
#############################################################################
#                   GNU General Public License v3.0                         #
#############################################################################
---
- name: Cloudflare | Add DNS Record | IPv6 | Remove unused AAAA DNS Record
  community.general.cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ dns_zone }}"
    state: absent
    type: AAAA
    record: "{{ dns_record }}"
  register: cloudflare_dns_v6_record_removal_status

- name: Cloudflare | Add DNS Record | IPv6 | Tasks on success
  when: cloudflare_dns_v6_record_removal_status is succeeded
  block:
    - name: Cloudflare | Add DNS Record | IPv6 | Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        dns_record_print: "{{ (dns_record == dns_zone) | ternary(dns_zone, dns_record + '.' + dns_zone) }}"

    - name: Cloudflare | Add DNS Record | IPv6 | Display DNS Record removal status
      ansible.builtin.debug:
        msg: "DNS AAAA Record for '{{ dns_record_print }}' was removed."
