#########################################################################
# Title:         Saltbox: qBittorrent | Legacy Tasks                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop '{{ qbittorrent_name }}.service'
  ansible.builtin.systemd_service:
    name: "{{ qbittorrent_name }}.service"
    state: stopped

- name: Remove '{{ qbittorrent_name }}.service' file
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ qbittorrent_name }}.service"
    state: absent
