#########################################################################
# Title:         Saltbox: Cloudplow | Disable Task                      #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and disable service
  ansible.builtin.systemd_service:
    name: "{{ cloudplow_service_name }}"
    state: stopped
    enabled: false
